#
#The drop chance must be between 0 and 100. Negative values act like 0 and values above 100 act like 100.
#
#---EXAMPLE FORMATTING---
#
#ELDER_GUARDIAN:
#  DIAMOND:
#    Chance: 50
#    Min_Amount: 1
#    Max_Amount: 3
#  EMERALD_BLOCK:
#    Chance: 30
#    Min_Amount: 2
#    Max_Amount: 5

#COW:
#  EMERALD:
#    Chance: 100
#    Min_Amount: 1
#    Max_Amount: 1